#!/bin/bash

if [ -e .env ]; then

	while read -r line || [[ -n "$line" ]]; do
	    toExport=${line%#*}
		case $toExport in
			(*[![:blank:]]*) 
				export "$toExport" ;;
		esac
	done < .env
fi

("${@:1}")