#!/bin/bash
echo "dotenv command line script"
echo "============"
echo "Starting installation..."
sudo curl -o /usr/bin/dotenv https://raw.githubusercontent.com/devinshively/dotenv/master/dotenv

echo "Updating permissions..."
sudo chmod +x /usr/bin/dotenv

echo "Installation complete..."