#!/bin/bash
echo "dotenv command line script"
echo "============"
echo "Starting installation..."
sudo curl -o /usr/local/bin/denv https://raw.githubusercontent.com/devinshively/denv/master/denv

echo "Updating permissions..."
sudo chmod +x /usr/local/bin/denv

echo "Installation complete..."